/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "contadores.v:1" *)
module synth_contadores(counter_out_synt, valid_out_synt, idx, push0, push1, push2, push3, idle, req, clk, reset);
  (* src = "contadores.v:44" *)
  wire [4:0] _000_;
  (* src = "contadores.v:44" *)
  wire [4:0] _001_;
  (* src = "contadores.v:44" *)
  wire [4:0] _002_;
  (* src = "contadores.v:44" *)
  wire [4:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  (* src = "contadores.v:6" *)
  input clk;
  (* src = "contadores.v:8" *)
  wire [4:0] counter0;
  (* src = "contadores.v:8" *)
  wire [4:0] counter1;
  (* src = "contadores.v:8" *)
  wire [4:0] counter2;
  (* src = "contadores.v:8" *)
  wire [4:0] counter3;
  (* src = "contadores.v:2" *)
  output [4:0] counter_out_synt;
  (* src = "contadores.v:6" *)
  input idle;
  (* src = "contadores.v:4" *)
  input [1:0] idx;
  (* src = "contadores.v:5" *)
  input push0;
  (* src = "contadores.v:5" *)
  input push1;
  (* src = "contadores.v:5" *)
  input push2;
  (* src = "contadores.v:5" *)
  input push3;
  (* src = "contadores.v:6" *)
  input req;
  (* src = "contadores.v:6" *)
  input reset;
  (* src = "contadores.v:3" *)
  output valid_out_synt;
  NOT _154_ (
    .A(idx[0]),
    .Y(_113_)
  );
  NOT _155_ (
    .A(idx[1]),
    .Y(_114_)
  );
  NOT _156_ (
    .A(counter3[0]),
    .Y(_115_)
  );
  NOT _157_ (
    .A(push3),
    .Y(_116_)
  );
  NOT _158_ (
    .A(counter3[1]),
    .Y(_117_)
  );
  NOT _159_ (
    .A(counter3[2]),
    .Y(_118_)
  );
  NOT _160_ (
    .A(counter3[4]),
    .Y(_119_)
  );
  NOT _161_ (
    .A(counter2[0]),
    .Y(_120_)
  );
  NOT _162_ (
    .A(push2),
    .Y(_121_)
  );
  NOT _163_ (
    .A(counter2[1]),
    .Y(_122_)
  );
  NOT _164_ (
    .A(counter2[2]),
    .Y(_123_)
  );
  NOT _165_ (
    .A(counter2[3]),
    .Y(_124_)
  );
  NOT _166_ (
    .A(counter2[4]),
    .Y(_125_)
  );
  NOT _167_ (
    .A(counter0[0]),
    .Y(_126_)
  );
  NOT _168_ (
    .A(push0),
    .Y(_127_)
  );
  NOT _169_ (
    .A(counter0[1]),
    .Y(_128_)
  );
  NOT _170_ (
    .A(counter0[2]),
    .Y(_129_)
  );
  NOT _171_ (
    .A(counter0[4]),
    .Y(_130_)
  );
  NOT _172_ (
    .A(counter1[0]),
    .Y(_131_)
  );
  NOT _173_ (
    .A(push1),
    .Y(_132_)
  );
  NOT _174_ (
    .A(counter1[1]),
    .Y(_133_)
  );
  NOT _175_ (
    .A(counter1[2]),
    .Y(_134_)
  );
  NOT _176_ (
    .A(counter1[4]),
    .Y(_135_)
  );
  NOT _177_ (
    .A(req),
    .Y(_136_)
  );
  NOT _178_ (
    .A(idle),
    .Y(_137_)
  );
  NOR _179_ (
    .A(_115_),
    .B(_116_),
    .Y(_138_)
  );
  NAND _180_ (
    .A(counter3[0]),
    .B(push3),
    .Y(_139_)
  );
  NOR _181_ (
    .A(counter3[0]),
    .B(push3),
    .Y(_140_)
  );
  NOT _182_ (
    .A(_140_),
    .Y(_141_)
  );
  NAND _183_ (
    .A(reset),
    .B(_141_),
    .Y(_142_)
  );
  NOR _184_ (
    .A(_138_),
    .B(_142_),
    .Y(_003_[0])
  );
  NOR _185_ (
    .A(_117_),
    .B(_139_),
    .Y(_143_)
  );
  NAND _186_ (
    .A(counter3[1]),
    .B(_138_),
    .Y(_144_)
  );
  NAND _187_ (
    .A(_117_),
    .B(_139_),
    .Y(_145_)
  );
  NAND _188_ (
    .A(reset),
    .B(_145_),
    .Y(_146_)
  );
  NOR _189_ (
    .A(_143_),
    .B(_146_),
    .Y(_003_[1])
  );
  NOR _190_ (
    .A(_118_),
    .B(_144_),
    .Y(_147_)
  );
  NAND _191_ (
    .A(_118_),
    .B(_144_),
    .Y(_148_)
  );
  NAND _192_ (
    .A(reset),
    .B(_148_),
    .Y(_149_)
  );
  NOR _193_ (
    .A(_147_),
    .B(_149_),
    .Y(_003_[2])
  );
  NAND _194_ (
    .A(counter3[3]),
    .B(_147_),
    .Y(_150_)
  );
  NOT _195_ (
    .A(_150_),
    .Y(_151_)
  );
  NOR _196_ (
    .A(counter3[3]),
    .B(_147_),
    .Y(_152_)
  );
  NOT _197_ (
    .A(_152_),
    .Y(_153_)
  );
  NAND _198_ (
    .A(reset),
    .B(_153_),
    .Y(_004_)
  );
  NOR _199_ (
    .A(_151_),
    .B(_004_),
    .Y(_003_[3])
  );
  NOR _200_ (
    .A(_119_),
    .B(_150_),
    .Y(_005_)
  );
  NAND _201_ (
    .A(_119_),
    .B(_150_),
    .Y(_006_)
  );
  NAND _202_ (
    .A(reset),
    .B(_006_),
    .Y(_007_)
  );
  NOR _203_ (
    .A(_005_),
    .B(_007_),
    .Y(_003_[4])
  );
  NOR _204_ (
    .A(_120_),
    .B(_121_),
    .Y(_008_)
  );
  NAND _205_ (
    .A(counter2[0]),
    .B(push2),
    .Y(_009_)
  );
  NOR _206_ (
    .A(counter2[0]),
    .B(push2),
    .Y(_010_)
  );
  NOT _207_ (
    .A(_010_),
    .Y(_011_)
  );
  NAND _208_ (
    .A(reset),
    .B(_011_),
    .Y(_012_)
  );
  NOR _209_ (
    .A(_008_),
    .B(_012_),
    .Y(_002_[0])
  );
  NOR _210_ (
    .A(_122_),
    .B(_009_),
    .Y(_013_)
  );
  NAND _211_ (
    .A(counter2[1]),
    .B(_008_),
    .Y(_014_)
  );
  NAND _212_ (
    .A(_122_),
    .B(_009_),
    .Y(_015_)
  );
  NAND _213_ (
    .A(reset),
    .B(_015_),
    .Y(_016_)
  );
  NOR _214_ (
    .A(_013_),
    .B(_016_),
    .Y(_002_[1])
  );
  NOR _215_ (
    .A(_123_),
    .B(_014_),
    .Y(_017_)
  );
  NAND _216_ (
    .A(_123_),
    .B(_014_),
    .Y(_018_)
  );
  NAND _217_ (
    .A(reset),
    .B(_018_),
    .Y(_019_)
  );
  NOR _218_ (
    .A(_017_),
    .B(_019_),
    .Y(_002_[2])
  );
  NAND _219_ (
    .A(counter2[3]),
    .B(_017_),
    .Y(_020_)
  );
  NOT _220_ (
    .A(_020_),
    .Y(_021_)
  );
  NOR _221_ (
    .A(counter2[3]),
    .B(_017_),
    .Y(_022_)
  );
  NOT _222_ (
    .A(_022_),
    .Y(_023_)
  );
  NAND _223_ (
    .A(reset),
    .B(_023_),
    .Y(_024_)
  );
  NOR _224_ (
    .A(_021_),
    .B(_024_),
    .Y(_002_[3])
  );
  NOR _225_ (
    .A(_125_),
    .B(_020_),
    .Y(_025_)
  );
  NAND _226_ (
    .A(_125_),
    .B(_020_),
    .Y(_026_)
  );
  NAND _227_ (
    .A(reset),
    .B(_026_),
    .Y(_027_)
  );
  NOR _228_ (
    .A(_025_),
    .B(_027_),
    .Y(_002_[4])
  );
  NOR _229_ (
    .A(_131_),
    .B(_132_),
    .Y(_028_)
  );
  NAND _230_ (
    .A(counter1[0]),
    .B(push1),
    .Y(_029_)
  );
  NOR _231_ (
    .A(counter1[0]),
    .B(push1),
    .Y(_030_)
  );
  NOT _232_ (
    .A(_030_),
    .Y(_031_)
  );
  NAND _233_ (
    .A(reset),
    .B(_031_),
    .Y(_032_)
  );
  NOR _234_ (
    .A(_028_),
    .B(_032_),
    .Y(_001_[0])
  );
  NOR _235_ (
    .A(_133_),
    .B(_029_),
    .Y(_033_)
  );
  NAND _236_ (
    .A(counter1[1]),
    .B(_028_),
    .Y(_034_)
  );
  NAND _237_ (
    .A(_133_),
    .B(_029_),
    .Y(_035_)
  );
  NAND _238_ (
    .A(reset),
    .B(_035_),
    .Y(_036_)
  );
  NOR _239_ (
    .A(_033_),
    .B(_036_),
    .Y(_001_[1])
  );
  NOR _240_ (
    .A(_134_),
    .B(_034_),
    .Y(_037_)
  );
  NAND _241_ (
    .A(_134_),
    .B(_034_),
    .Y(_038_)
  );
  NAND _242_ (
    .A(reset),
    .B(_038_),
    .Y(_039_)
  );
  NOR _243_ (
    .A(_037_),
    .B(_039_),
    .Y(_001_[2])
  );
  NAND _244_ (
    .A(counter1[3]),
    .B(_037_),
    .Y(_040_)
  );
  NOT _245_ (
    .A(_040_),
    .Y(_041_)
  );
  NOR _246_ (
    .A(counter1[3]),
    .B(_037_),
    .Y(_042_)
  );
  NOT _247_ (
    .A(_042_),
    .Y(_043_)
  );
  NAND _248_ (
    .A(reset),
    .B(_043_),
    .Y(_044_)
  );
  NOR _249_ (
    .A(_041_),
    .B(_044_),
    .Y(_001_[3])
  );
  NOR _250_ (
    .A(_135_),
    .B(_040_),
    .Y(_045_)
  );
  NAND _251_ (
    .A(_135_),
    .B(_040_),
    .Y(_046_)
  );
  NAND _252_ (
    .A(reset),
    .B(_046_),
    .Y(_047_)
  );
  NOR _253_ (
    .A(_045_),
    .B(_047_),
    .Y(_001_[4])
  );
  NOR _254_ (
    .A(_126_),
    .B(_127_),
    .Y(_048_)
  );
  NAND _255_ (
    .A(counter0[0]),
    .B(push0),
    .Y(_049_)
  );
  NOR _256_ (
    .A(counter0[0]),
    .B(push0),
    .Y(_050_)
  );
  NOT _257_ (
    .A(_050_),
    .Y(_051_)
  );
  NAND _258_ (
    .A(reset),
    .B(_051_),
    .Y(_052_)
  );
  NOR _259_ (
    .A(_048_),
    .B(_052_),
    .Y(_000_[0])
  );
  NOR _260_ (
    .A(_128_),
    .B(_049_),
    .Y(_053_)
  );
  NAND _261_ (
    .A(counter0[1]),
    .B(_048_),
    .Y(_054_)
  );
  NAND _262_ (
    .A(_128_),
    .B(_049_),
    .Y(_055_)
  );
  NAND _263_ (
    .A(reset),
    .B(_055_),
    .Y(_056_)
  );
  NOR _264_ (
    .A(_053_),
    .B(_056_),
    .Y(_000_[1])
  );
  NOR _265_ (
    .A(_129_),
    .B(_054_),
    .Y(_057_)
  );
  NAND _266_ (
    .A(_129_),
    .B(_054_),
    .Y(_058_)
  );
  NAND _267_ (
    .A(reset),
    .B(_058_),
    .Y(_059_)
  );
  NOR _268_ (
    .A(_057_),
    .B(_059_),
    .Y(_000_[2])
  );
  NAND _269_ (
    .A(counter0[3]),
    .B(_057_),
    .Y(_060_)
  );
  NOT _270_ (
    .A(_060_),
    .Y(_061_)
  );
  NOR _271_ (
    .A(counter0[3]),
    .B(_057_),
    .Y(_062_)
  );
  NOT _272_ (
    .A(_062_),
    .Y(_063_)
  );
  NAND _273_ (
    .A(reset),
    .B(_063_),
    .Y(_064_)
  );
  NOR _274_ (
    .A(_061_),
    .B(_064_),
    .Y(_000_[3])
  );
  NOR _275_ (
    .A(_130_),
    .B(_060_),
    .Y(_065_)
  );
  NAND _276_ (
    .A(_130_),
    .B(_060_),
    .Y(_066_)
  );
  NAND _277_ (
    .A(reset),
    .B(_066_),
    .Y(_067_)
  );
  NOR _278_ (
    .A(_065_),
    .B(_067_),
    .Y(_000_[4])
  );
  NOR _279_ (
    .A(_136_),
    .B(_137_),
    .Y(valid_out_synt)
  );
  NOR _280_ (
    .A(_113_),
    .B(idx[1]),
    .Y(_068_)
  );
  NAND _281_ (
    .A(_113_),
    .B(idx[1]),
    .Y(_069_)
  );
  NOT _282_ (
    .A(_069_),
    .Y(_070_)
  );
  NOR _283_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _284_ (
    .A(counter3[0]),
    .B(_071_),
    .Y(_072_)
  );
  NOR _285_ (
    .A(_120_),
    .B(_069_),
    .Y(_073_)
  );
  NOR _286_ (
    .A(_113_),
    .B(counter1[0]),
    .Y(_074_)
  );
  NAND _287_ (
    .A(_113_),
    .B(_114_),
    .Y(_075_)
  );
  NOR _288_ (
    .A(idx[1]),
    .B(_074_),
    .Y(_076_)
  );
  NOR _289_ (
    .A(_073_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _290_ (
    .A(_072_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _291_ (
    .A(counter0[0]),
    .B(_075_),
    .Y(_079_)
  );
  NAND _292_ (
    .A(valid_out_synt),
    .B(_078_),
    .Y(_080_)
  );
  NOR _293_ (
    .A(_079_),
    .B(_080_),
    .Y(counter_out_synt[0])
  );
  NAND _294_ (
    .A(counter3[1]),
    .B(_071_),
    .Y(_081_)
  );
  NOR _295_ (
    .A(_122_),
    .B(_069_),
    .Y(_082_)
  );
  NOR _296_ (
    .A(_113_),
    .B(counter1[1]),
    .Y(_083_)
  );
  NOR _297_ (
    .A(idx[1]),
    .B(_083_),
    .Y(_084_)
  );
  NOR _298_ (
    .A(_082_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _299_ (
    .A(_081_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _300_ (
    .A(counter0[1]),
    .B(_075_),
    .Y(_087_)
  );
  NAND _301_ (
    .A(valid_out_synt),
    .B(_086_),
    .Y(_088_)
  );
  NOR _302_ (
    .A(_087_),
    .B(_088_),
    .Y(counter_out_synt[1])
  );
  NAND _303_ (
    .A(counter3[2]),
    .B(_071_),
    .Y(_089_)
  );
  NOR _304_ (
    .A(_123_),
    .B(_069_),
    .Y(_090_)
  );
  NOR _305_ (
    .A(_113_),
    .B(counter1[2]),
    .Y(_091_)
  );
  NOR _306_ (
    .A(idx[1]),
    .B(_091_),
    .Y(_092_)
  );
  NOR _307_ (
    .A(_090_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _308_ (
    .A(_089_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _309_ (
    .A(counter0[2]),
    .B(_075_),
    .Y(_095_)
  );
  NAND _310_ (
    .A(valid_out_synt),
    .B(_094_),
    .Y(_096_)
  );
  NOR _311_ (
    .A(_095_),
    .B(_096_),
    .Y(counter_out_synt[2])
  );
  NAND _312_ (
    .A(counter3[3]),
    .B(_071_),
    .Y(_097_)
  );
  NOR _313_ (
    .A(_124_),
    .B(_069_),
    .Y(_098_)
  );
  NOR _314_ (
    .A(_113_),
    .B(counter1[3]),
    .Y(_099_)
  );
  NOR _315_ (
    .A(idx[1]),
    .B(_099_),
    .Y(_100_)
  );
  NOR _316_ (
    .A(_098_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _317_ (
    .A(_097_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _318_ (
    .A(counter0[3]),
    .B(_075_),
    .Y(_103_)
  );
  NAND _319_ (
    .A(valid_out_synt),
    .B(_102_),
    .Y(_104_)
  );
  NOR _320_ (
    .A(_103_),
    .B(_104_),
    .Y(counter_out_synt[3])
  );
  NAND _321_ (
    .A(counter3[4]),
    .B(_071_),
    .Y(_105_)
  );
  NOR _322_ (
    .A(_125_),
    .B(_069_),
    .Y(_106_)
  );
  NOR _323_ (
    .A(_113_),
    .B(counter1[4]),
    .Y(_107_)
  );
  NOR _324_ (
    .A(idx[1]),
    .B(_107_),
    .Y(_108_)
  );
  NOR _325_ (
    .A(_106_),
    .B(_108_),
    .Y(_109_)
  );
  NAND _326_ (
    .A(_105_),
    .B(_109_),
    .Y(_110_)
  );
  NOR _327_ (
    .A(counter0[4]),
    .B(_075_),
    .Y(_111_)
  );
  NAND _328_ (
    .A(valid_out_synt),
    .B(_110_),
    .Y(_112_)
  );
  NOR _329_ (
    .A(_111_),
    .B(_112_),
    .Y(counter_out_synt[4])
  );
  (* src = "contadores.v:44" *)
  DFF _330_ (
    .C(clk),
    .D(_000_[0]),
    .Q(counter0[0])
  );
  (* src = "contadores.v:44" *)
  DFF _331_ (
    .C(clk),
    .D(_000_[1]),
    .Q(counter0[1])
  );
  (* src = "contadores.v:44" *)
  DFF _332_ (
    .C(clk),
    .D(_000_[2]),
    .Q(counter0[2])
  );
  (* src = "contadores.v:44" *)
  DFF _333_ (
    .C(clk),
    .D(_000_[3]),
    .Q(counter0[3])
  );
  (* src = "contadores.v:44" *)
  DFF _334_ (
    .C(clk),
    .D(_000_[4]),
    .Q(counter0[4])
  );
  (* src = "contadores.v:44" *)
  DFF _335_ (
    .C(clk),
    .D(_001_[0]),
    .Q(counter1[0])
  );
  (* src = "contadores.v:44" *)
  DFF _336_ (
    .C(clk),
    .D(_001_[1]),
    .Q(counter1[1])
  );
  (* src = "contadores.v:44" *)
  DFF _337_ (
    .C(clk),
    .D(_001_[2]),
    .Q(counter1[2])
  );
  (* src = "contadores.v:44" *)
  DFF _338_ (
    .C(clk),
    .D(_001_[3]),
    .Q(counter1[3])
  );
  (* src = "contadores.v:44" *)
  DFF _339_ (
    .C(clk),
    .D(_001_[4]),
    .Q(counter1[4])
  );
  (* src = "contadores.v:44" *)
  DFF _340_ (
    .C(clk),
    .D(_002_[0]),
    .Q(counter2[0])
  );
  (* src = "contadores.v:44" *)
  DFF _341_ (
    .C(clk),
    .D(_002_[1]),
    .Q(counter2[1])
  );
  (* src = "contadores.v:44" *)
  DFF _342_ (
    .C(clk),
    .D(_002_[2]),
    .Q(counter2[2])
  );
  (* src = "contadores.v:44" *)
  DFF _343_ (
    .C(clk),
    .D(_002_[3]),
    .Q(counter2[3])
  );
  (* src = "contadores.v:44" *)
  DFF _344_ (
    .C(clk),
    .D(_002_[4]),
    .Q(counter2[4])
  );
  (* src = "contadores.v:44" *)
  DFF _345_ (
    .C(clk),
    .D(_003_[0]),
    .Q(counter3[0])
  );
  (* src = "contadores.v:44" *)
  DFF _346_ (
    .C(clk),
    .D(_003_[1]),
    .Q(counter3[1])
  );
  (* src = "contadores.v:44" *)
  DFF _347_ (
    .C(clk),
    .D(_003_[2]),
    .Q(counter3[2])
  );
  (* src = "contadores.v:44" *)
  DFF _348_ (
    .C(clk),
    .D(_003_[3]),
    .Q(counter3[3])
  );
  (* src = "contadores.v:44" *)
  DFF _349_ (
    .C(clk),
    .D(_003_[4]),
    .Q(counter3[4])
  );
endmodule
