/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 10.2.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "contadores.v:1" *)
module contadores_synth(data, valid, fifo_data_out0, fifo_data_out1, fifo_data_out2, fifo_data_out3, req, idx, estado_FSM, rst, clk);
  (* src = "contadores.v:30" *)
  wire [4:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "contadores.v:12" *)
  input clk;
  (* src = "contadores.v:18" *)
  wire [4:0] conteo0;
  (* src = "contadores.v:19" *)
  wire [4:0] conteo1;
  (* src = "contadores.v:20" *)
  wire [4:0] conteo2;
  (* src = "contadores.v:21" *)
  wire [4:0] conteo3;
  (* src = "contadores.v:2" *)
  output [4:0] data;
  (* src = "contadores.v:10" *)
  input [3:0] estado_FSM;
  (* src = "contadores.v:4" *)
  input [9:0] fifo_data_out0;
  (* src = "contadores.v:5" *)
  input [9:0] fifo_data_out1;
  (* src = "contadores.v:6" *)
  input [9:0] fifo_data_out2;
  (* src = "contadores.v:7" *)
  input [9:0] fifo_data_out3;
  (* src = "contadores.v:9" *)
  input [1:0] idx;
  (* src = "contadores.v:8" *)
  input req;
  (* src = "contadores.v:11" *)
  input rst;
  (* src = "contadores.v:3" *)
  output valid;
  NOT _16_ (
    .A(clk),
    .Y(_05_)
  );
  NOT _17_ (
    .A(estado_FSM[3]),
    .Y(_06_)
  );
  NOR _18_ (
    .A(estado_FSM[0]),
    .B(estado_FSM[1]),
    .Y(_07_)
  );
  NOT _19_ (
    .A(_07_),
    .Y(_08_)
  );
  NAND _20_ (
    .A(_06_),
    .B(estado_FSM[2]),
    .Y(_09_)
  );
  NOR _21_ (
    .A(_08_),
    .B(_09_),
    .Y(valid)
  );
  NAND _22_ (
    .A(req),
    .B(rst),
    .Y(_10_)
  );
  NAND _23_ (
    .A(data[0]),
    .B(_10_),
    .Y(_11_)
  );
  NOT _24_ (
    .A(_11_),
    .Y(_00_[0])
  );
  NAND _25_ (
    .A(data[1]),
    .B(_10_),
    .Y(_12_)
  );
  NOT _26_ (
    .A(_12_),
    .Y(_00_[1])
  );
  NAND _27_ (
    .A(data[2]),
    .B(_10_),
    .Y(_13_)
  );
  NOT _28_ (
    .A(_13_),
    .Y(_00_[2])
  );
  NAND _29_ (
    .A(data[3]),
    .B(_10_),
    .Y(_14_)
  );
  NOT _30_ (
    .A(_14_),
    .Y(_00_[3])
  );
  NAND _31_ (
    .A(data[4]),
    .B(_10_),
    .Y(_15_)
  );
  NOT _32_ (
    .A(_15_),
    .Y(_00_[4])
  );
  NOT _33_ (
    .A(clk),
    .Y(_01_)
  );
  NOT _34_ (
    .A(clk),
    .Y(_02_)
  );
  NOT _35_ (
    .A(clk),
    .Y(_03_)
  );
  NOT _36_ (
    .A(clk),
    .Y(_04_)
  );
  (* src = "contadores.v:30" *)
  DFF _37_ (
    .C(_01_),
    .D(_00_[0]),
    .Q(data[0])
  );
  (* src = "contadores.v:30" *)
  DFF _38_ (
    .C(_02_),
    .D(_00_[1]),
    .Q(data[1])
  );
  (* src = "contadores.v:30" *)
  DFF _39_ (
    .C(_03_),
    .D(_00_[2]),
    .Q(data[2])
  );
  (* src = "contadores.v:30" *)
  DFF _40_ (
    .C(_04_),
    .D(_00_[3]),
    .Q(data[3])
  );
  (* src = "contadores.v:30" *)
  DFF _41_ (
    .C(_05_),
    .D(_00_[4]),
    .Q(data[4])
  );
  assign conteo0 = 5'h00;
  assign conteo1 = 5'h00;
  assign conteo2 = 5'h00;
  assign conteo3 = 5'h00;
endmodule
